#!/usr/bin/env php
<?php

require __DIR__.'/autoload.php';

use \Symfony\Component\Console\Application;

$application = new Application;

$application->add(new \SlimExample\Modules\Core\Commands\ServerCommand());
$application->add(new \SlimExample\Modules\Core\Commands\SubscriberCommand);
$application->add(new \SlimExample\Modules\Core\Commands\UpdateApiDocCommand);
$application->add(new \SlimExample\Modules\Core\Commands\Migrations\InitCommand);
$application->add(new \SlimExample\Modules\Core\Commands\Migrations\MigrationCommand);
$application->add(new \SlimExample\Modules\Core\Commands\Migrations\SeedCommand);
$application->add(new \SlimExample\Modules\Core\Commands\Migrations\StatusCommand);
$application->add(new \SlimExample\Modules\Core\Commands\Migrations\SeedCreateCommand);
$application->add(new \SlimExample\Modules\Core\Commands\Migrations\RollbackCommand);
$application->add(new \SlimExample\Modules\Core\Commands\Migrations\MigrationCreateCommand);

$application->run();