#!/usr/bin/env php
<?php

require __DIR__.'/autoload.php';

use \Symfony\Component\Console\Application;

$application = new Application;

$application->add(new \SlimExample\Modules\Core\Commands\ServerCommand());
$application->add(new \SlimExample\Modules\Migrations\Commands\InitCommand);
$application->add(new \SlimExample\Modules\Migrations\Commands\MigrationCommand);
$application->add(new \SlimExample\Modules\Migrations\Commands\SeedCommand);
$application->add(new \SlimExample\Modules\Migrations\Commands\SeedCreateCommand);

$application->run();