version: "3"

services:
  webapp_php7_fpm_nginx:
    container_name: "slim-app-example"
    image: webapp/webapp:1.0.0
    expose:
      - "80"
    ports:
      - "80:80"
    build:
      dockerfile: ./php7-fpm+nginx/dockerfile
      context: .
    stdin_open: true
    tty: true
    networks:
      app_network:
        ipv4_address: 192.168.80.10

    volumes:
      - "../code:/var/www/code"
      - "./php7-fpm+nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./php7-fpm+nginx/sites-available/app.nginx.conf:/etc/nginx/sites-available/app.conf"
      - "./php7-fpm+nginx/sites-available/app.nginx.conf:/etc/nginx/sites-enabled/app.conf"
    restart: always

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "exampleapp"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      app_network:
        ipv4_address: 192.168.80.11

    volumes:
      - ./mysql_data:/var/lib/mysql

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmqdata:/var/lib/rabbitmq      
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    networks:
      app_network:
        ipv4_address: 192.168.80.12

  swagger-ui:
    image: swaggerapi/swagger-ui:v3.45.1
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ../code/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
    networks:
      app_network:
        ipv4_address: 192.168.80.13

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.80.0/24
