version: "3"

services:
  webapp_php7_fpm_nginx:
    container_name: "slim-app-example"
    image: webapp/webapp:1.0.0
    expose:
      - "80"
    ports:
      - "80:80"
    build:
      dockerfile: ./php7-fpm+nginx/dockerfile
      context: .
    stdin_open: true
    tty: true
    networks:
      - app_network
    volumes:
      - "../code:/var/www/code"
      - "./php7-fpm+nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./php7-fpm+nginx/sites-available/app.nginx.conf:/etc/nginx/sites-available/app.conf"
      - "./php7-fpm+nginx/sites-available/app.nginx.conf:/etc/nginx/sites-enabled/app.conf"
    restart: always

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.80.0/24
